
const products = [
    { id: '1', name: 'Product 1', price: 'R119.99', details: 'Details of Product 1' },
    { id: '2', name: 'Product 2', price: 'R229.99', details: 'Details of Product 2' },
    { id: '3', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '4', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '5', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '6', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '7', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '8', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '9', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '10', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '11', name: 'Product 1', price: 'R119.99', details: 'Details of Product 1' },
    { id: '12', name: 'Product 2', price: 'R229.99', details: 'Details of Product 2' },
    { id: '13', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '14', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '15', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '16', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '17', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '18', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '19', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '20', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '21', name: 'Product 1', price: 'R119.99', details: 'Details of Product 1' },
    { id: '22', name: 'Product 2', price: 'R229.99', details: 'Details of Product 2' },
    { id: '23', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '24', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '25', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '26', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '27', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '28', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '29', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '30', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '31', name: 'Product 1', price: 'R119.99', details: 'Details of Product 1' },
    { id: '32', name: 'Product 2', price: 'R229.99', details: 'Details of Product 2' },
    { id: '33', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '34', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '35', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
    { id: '36', name: 'Product 6', price: 'R669.99', details: 'Details of Product 6' },
    { id: '37', name: 'Product 3', price: 'R339.99', details: 'Details of Product 3' },
    { id: '38', name: 'Product 4', price: 'R449.99', details: 'Details of Product 4' },
    { id: '39', name: 'Product 5', price: 'R559.99', details: 'Details of Product 5' },
   
  ];
  
  export default products;