const products = [
  { id: '1', name: 'Fridge', price: 'R1199.99', details: 'Energy-efficient, 350L capacity.' },
  { id: '2', name: 'Bag', price: 'R229.99', details: 'Durable and stylish, perfect for travel.' },
  { id: '3', name: 'Bottle', price: 'R49.99', details: '500ml, BPA-free, reusable.' },
  { id: '4', name: 'Smartphone', price: 'R4499.99', details: 'Latest model with 5G support.' },
  { id: '5', name: 'Headphones', price: 'R559.99', details: 'Noise-cancelling, over-ear design.' },
  { id: '6', name: 'Laptop', price: 'R6699.99', details: '15-inch, 16GB RAM, 512GB SSD.' },
  { id: '7', name: 'Watch', price: 'R339.99', details: 'Water-resistant, digital display.' },
  { id: '8', name: 'Camera', price: 'R449.99', details: '12MP, 4K video recording.' },
  { id: '9', name: 'Tablet', price: 'R559.99', details: '10-inch, 64GB storage.' },
  { id: '10', name: 'Gaming Console', price: 'R669.99', details: 'Latest generation, 1TB storage.' },
  { id: '11', name: 'Microwave', price: 'R119.99', details: '800W, compact size.' },
  { id: '12', name: 'Blender', price: 'R229.99', details: 'Multi-speed, 1.5L capacity.' },
  { id: '13', name: 'Coffee Maker', price: 'R339.99', details: 'Programmable, 12-cup capacity.' },
  { id: '14', name: 'Toaster', price: 'R449.99', details: '4-slice, stainless steel.' },
  { id: '15', name: 'Air Fryer', price: 'R559.99', details: 'Digital display, 5.5L capacity.' },
  { id: '16', name: 'Vacuum Cleaner', price: 'R669.99', details: 'Cordless, powerful suction.' },
  { id: '17', name: 'Hair Dryer', price: 'R339.99', details: 'Ionic technology, 1800W.' },
  { id: '18', name: 'Electric Kettle', price: 'R449.99', details: '1.7L, rapid boil.' },
  { id: '19', name: 'Iron', price: 'R559.99', details: 'Steam, anti-drip feature.' },
  { id: '20', name: 'Fan', price: 'R669.99', details: 'Oscillating, 3-speed settings.' },
  { id: '21', name: 'Heater', price: 'R119.99', details: 'Portable, 1500W.' },
  { id: '22', name: 'Smart Light Bulb', price: 'R229.99', details: 'WiFi enabled, color changing.' },
  { id: '23', name: 'Bluetooth Speaker', price: 'R339.99', details: 'Portable, waterproof.' },
  { id: '24', name: 'Smart Watch', price: 'R449.99', details: 'Fitness tracking, GPS.' },
  { id: '25', name: 'Electric Toothbrush', price: 'R559.99', details: 'Rechargeable, multiple modes.' },
  { id: '26', name: 'Fitness Tracker', price: 'R669.99', details: 'Heart rate monitor, sleep tracking.' },
  { id: '27', name: 'Desk Lamp', price: 'R339.99', details: 'LED, adjustable brightness.' },
  { id: '28', name: 'Printer', price: 'R449.99', details: 'Wireless, all-in-one.' },
  { id: '29', name: 'Router', price: 'R559.99', details: 'Dual-band, high speed.' },
  { id: '30', name: 'Drone', price: 'R669.99', details: 'Camera, long battery life.' },
  { id: '31', name: 'Sewing Machine', price: 'R119.99', details: 'Portable, easy to use.' },
  { id: '32', name: 'Air Purifier', price: 'R229.99', details: 'HEPA filter, quiet operation.' },
  { id: '33', name: 'Electric Grill', price: 'R339.99', details: 'Non-stick, adjustable temperature.' },
  { id: '34', name: 'Slow Cooker', price: 'R449.99', details: '6-quart capacity, digital controls.' },
  { id: '35', name: 'Rice Cooker', price: 'R559.99', details: '10-cup capacity, keep warm feature.' },
  { id: '36', name: 'Pressure Cooker', price: 'R669.99', details: 'Multi-function, stainless steel.' },
  { id: '37', name: 'Bread Maker', price: 'R339.99', details: '12 settings, non-stick pan.' },
  { id: '38', name: 'Water Dispenser', price: 'R449.99', details: 'Hot and cold water, bottom load.' },
  { id: '39', name: 'Dehumidifier', price: 'R559.99', details: 'Portable, quiet operation.' },
];

  export default products;