const products = [
  {
    id: "1",
    name: "Fridge",
    price: "R1199.99",
    details: "Energy-efficient, 350L capacity.",
    location: "Johannesburg",
  },
  {
    id: "2",
    name: "Bag",
    price: "R229.99",
    details: "Durable and stylish, perfect for travel.",
    location: "Cape Town",
  },
  {
    id: "3",
    name: "Bottle",
    price: "R49.99",
    details: "500ml, BPA-free, reusable.",
    location: "Durban",
  },
  {
    id: "4",
    name: "Smartphone",
    price: "R4499.99",
    details: "Latest model with 5G support.",
    location: "Pretoria",
  },
  {
    id: "5",
    name: "Headphones",
    price: "R559.99",
    details: "Noise-cancelling, over-ear design.",
    location: "Port Elizabeth",
  },
  {
    id: "6",
    name: "Laptop",
    price: "R6699.99",
    details: "15-inch, 16GB RAM, 512GB SSD.",
    location: "Bloemfontein",
  },
  {
    id: "7",
    name: "Watch",
    price: "R339.99",
    details: "Water-resistant, digital display.",
    location: "Johannesburg",
  },
  {
    id: "8",
    name: "Camera",
    price: "R449.99",
    details: "12MP, 4K video recording.",
    location: "Cape Town",
  },
  {
    id: "9",
    name: "Tablet",
    price: "R559.99",
    details: "10-inch, 64GB storage.",
    location: "Durban",
  },
  {
    id: "10",
    name: "Gaming Console",
    price: "R669.99",
    details: "Latest generation, 1TB storage.",
    location: "Pretoria",
  },
  {
    id: "11",
    name: "Microwave",
    price: "R119.99",
    details: "800W, compact size.",
    location: "Port Elizabeth",
  },
  {
    id: "12",
    name: "Blender",
    price: "R229.99",
    details: "Multi-speed, 1.5L capacity.",
    location: "Bloemfontein",
  },
  {
    id: "13",
    name: "Coffee Maker",
    price: "R339.99",
    details: "Programmable, 12-cup capacity.",
    location: "Johannesburg",
  },
  {
    id: "14",
    name: "Toaster",
    price: "R449.99",
    details: "4-slice, stainless steel.",
    location: "Cape Town",
  },
  {
    id: "15",
    name: "Air Fryer",
    price: "R559.99",
    details: "Digital display, 5.5L capacity.",
    location: "Durban",
  },
  {
    id: "16",
    name: "Vacuum Cleaner",
    price: "R669.99",
    details: "Cordless, powerful suction.",
    location: "Pretoria",
  },
  {
    id: "17",
    name: "Hair Dryer",
    price: "R339.99",
    details: "Ionic technology, 1800W.",
    location: "Port Elizabeth",
  },
  {
    id: "18",
    name: "Electric Kettle",
    price: "R449.99",
    details: "1.7L, rapid boil.",
    location: "Bloemfontein",
  },
  {
    id: "19",
    name: "Iron",
    price: "R559.99",
    details: "Steam, anti-drip feature.",
    location: "Johannesburg",
  },
  {
    id: "20",
    name: "Fan",
    price: "R669.99",
    details: "Oscillating, 3-speed settings.",
    location: "Cape Town",
  },
  {
    id: "21",
    name: "Heater",
    price: "R119.99",
    details: "Portable, 1500W.",
    location: "Durban",
  },
  {
    id: "22",
    name: "Smart Light Bulb",
    price: "R229.99",
    details: "WiFi enabled, color changing.",
    location: "Pretoria",
  },
  {
    id: "23",
    name: "Bluetooth Speaker",
    price: "R339.99",
    details: "Portable, waterproof.",
    location: "Port Elizabeth",
  },
  {
    id: "24",
    name: "Smart Watch",
    price: "R449.99",
    details: "Fitness tracking, GPS.",
    location: "Bloemfontein",
  },
  {
    id: "25",
    name: "Electric Toothbrush",
    price: "R559.99",
    details: "Rechargeable, multiple modes.",
    location: "Johannesburg",
  },
  {
    id: "26",
    name: "Fitness Tracker",
    price: "R669.99",
    details: "Heart rate monitor, sleep tracking.",
    location: "Cape Town",
  },
  {
    id: "27",
    name: "Desk Lamp",
    price: "R339.99",
    details: "LED, adjustable brightness.",
    location: "Durban",
  },
  {
    id: "28",
    name: "Printer",
    price: "R449.99",
    details: "Wireless, all-in-one.",
    location: "Pretoria",
  },
  {
    id: "29",
    name: "Router",
    price: "R559.99",
    details: "Dual-band, high speed.",
    location: "Port Elizabeth",
  },
  {
    id: "30",
    name: "Drone",
    price: "R669.99",
    details: "Camera, long battery life.",
    location: "Bloemfontein",
  },
  {
    id: "31",
    name: "Sewing Machine",
    price: "R119.99",
    details: "Portable, easy to use.",
    location: "Johannesburg",
  },
  {
    id: "32",
    name: "Air Purifier",
    price: "R229.99",
    details: "HEPA filter, quiet operation.",
    location: "Cape Town",
  },
  {
    id: "33",
    name: "Electric Grill",
    price: "R339.99",
    details: "Non-stick, adjustable temperature.",
    location: "Durban",
  },
  {
    id: "34",
    name: "Slow Cooker",
    price: "R449.99",
    details: "6-quart capacity, digital controls.",
    location: "Pretoria",
  },
  {
    id: "35",
    name: "Rice Cooker",
    price: "R559.99",
    details: "10-cup capacity, keep warm feature.",
    location: "Port Elizabeth",
  },
  {
    id: "36",
    name: "Pressure Cooker",
    price: "R669.99",
    details: "Multi-function, stainless steel.",
    location: "Bloemfontein",
  },
  {
    id: "37",
    name: "Bread Maker",
    price: "R339.99",
    details: "12 settings, non-stick pan.",
    location: "Johannesburg",
  },
  {
    id: "38",
    name: "Water Dispenser",
    price: "R449.99",
    details: "Hot and cold water, bottom load.",
    location: "Cape Town",
  },
  {
    id: "39",
    name: "Dehumidifier",
    price: "R559.99",
    details: "Portable, quiet operation.",
    location: "Durban",
  },
];

export default products;
